[project]
name = "orchestration-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk>=0.2.7",
    "asyncclick>=8.1.8",
    "click>=8.1.8",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "google-adk>=1.0.0",
    "google-genai>=1.11.0",
    "httpx>=0.28.1",
    "httpx-sse>=0.4.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
    "starlette>=0.46.2",
    "uvicorn>=0.34.2",
]
